  name: 'GitHub Event Object Parser'
  description: 'Attempts to translate GHs event object into a human readable message'
  inputs:
    job-status:
      description: 'The current status of the job.'
      required: true
    run-id:
      description: 'A unique number for each run within a repository'
      required: true
  outputs:
    blocks:
      description: 'Human readable message with action result'
  runs:
    using: 'node12'
    main: 'lib/index.js'
